<body>

	<div>Un internaute souhaite prendre un rendez-vous :</div>
	
	<dl>
		<dt>Nom</dt><dd><?php echo $this->nom; ?></dd>
		<dt>Prénom</dt><dd><?php echo $this->prenom; ?></dd>
		<dt>Téléphone</dt><dd><?php echo $this->telephone; ?></dd>
		<dt>Email</dt><dd><?php echo $this->email; ?></dd>
		<dt>Date Souhaitée</dt><dd><?php echo $this->dateSouhaitee; ?></dd>
		<dt>Plage Horaire Souhaitée</dt><dd><?php echo $this->horaireSouhaite; ?></dd>
		<dt>Type Intervention</dt><dd><?php echo $this->typeIntervention; ?></dd>
		<dt>Marque/Modele</dt><dd><?php echo $this->descVehicule; ?></dd>
		<dt>Immatriculation</dt><dd><?php echo $this->immatriculation; ?></dd>
	</dl>

</body>