<body>

	<div>Un internaute souhaite commander un véhicule neuf :</div>
	
	<dl>
		<dt>Nom</dt><dd><?php echo $this->nom; ?></dd>
		<dt>Prenom</dt><dd><?php echo $this->prenom; ?></dd>
		<dt>Email</dt><dd><?php echo $this->email; ?></dd>
		<dt>Téléphone</dt><dd><?php echo $this->telephone; ?></dd>
		<dt>Marque</dt><dd><?php echo $this->marque; ?></dd>
		<dt>Modèle</dt><dd><?php echo $this->modele; ?></dd>
		<dt>Type</dt><dd><?php echo $this->type; ?></dd>
		<dt>Portes</dt><dd><?php echo $this->porte; ?></dd>
		<dt>Energie</dt><dd><?php echo $this->energie; ?></dd>
		<dt>Transmission</dt><dd><?php echo $this->transmission; ?></dd>
		<dt>Commentaires</dt><dd><?php echo $this->commentaires; ?></dd>
	</dl>

</body>