	<div class="container clearfix">
		<div id="default-page" class="main-con">
			<div class="title-nav">
				<h2 style="background-position:0 -279px">Entretien et Révision</h2>
			</div>
		<div class="content" style="margin-bottom:50px">
		
		<p class="blc-txt">Prenez soin de votre véhicule et votre véhicule vous le rendra. Maintenez le bon fonctionnement de votre voiture grâce à notre expérience.</p>
		
			<div class="divpic">
			<img src="<?php echo $this->baseUrl('image/automonp/entretien1.jpg')?>" alt="entretien revision voiture" class="pic"/>
			<img src="<?php echo $this->baseUrl('image/automonp/entretien2.jpg')?>" alt="entretien revision voiture" class="pic"/>
			<img src="<?php echo $this->baseUrl('image/automonp/entretien3.jpg')?>" alt="entretien revision voiture" class="pic"/>
			</div>

<div>

<div class="center demo" style="display:none">
	<a href="<?php echo $this->url(array('controller'=>'service','action'=>'forfaits'),'default',true) ?>">Voir Tous Nos Forfaits</a>
</div>

<div style="margin-top:20px;" id="accordion">
	<h3><a href="#">Plan d'entretien Véhicules particuliers</a></h3>
	<div>
		<p>
		Votre <strong>Garage AUTOMOBILES MONPLAISIR</strong> connaît la technologie de votre véhicule. De plus, il est équipé des outils de pointe nécessaires pour vous assurer des réparations de qualité optimale à un prix juste.
		</p>
		<br/>
		<p>
		Le carnet d’entretien et de garantie décrit le plan d’entretien préconisé par le constructeur afin de garantir à votre véhicule un maximum de fiabilité.<br/>
		Quel que soit votre modèle et votre utilisation, le plan d’entretien de votre véhicule est conçu pour assurer sa longévité et maintenir ses performances au meilleur niveau.
		</p>
	</div>
	<h3><a href="#">La révision voiture se compose généralement des éléments suivants :</a></h3>
	<div>
		<p>
		<p>	&bull; Une vidange avec changement du filtre à huile.</p>
		<p>	&bull; L'échange du filtre à pollen si vous avez un système de climatisation.</p>
		<p>	&bull; Le remplacement du filtre à air.</p>
		<p> &bull; La mise à niveau des liquides (lave-vitres, refroidissement, de freins, de direction assistée...).</p>
		<p>	&bull; Une lecture de la mémoire du boitier électronique de votre voiture.</p>
		<p>	&bull; Un essai routier.</p>
		<p>	&bull; Et enfin des contrôles sur l'ensemble des éléments de sécurité de votre voiture (feux,pneu auto, plaquettes de frein, système de direction, amortisseurs, balais essuie-glace...).</p>
		<br/>
		<p>
		Suite au contrôle de ces éléments, nous pouvons vous proposer d'échanger les pièces qui montrent des signes de fatigue ou qui ont atteint les limites légales d'usure (exemple : moins de 1,6 mm pour la profondeur des sillons de vos pneus auto).<br/>
		Ensuite selon le modèle, l'âge et le kilométrage se rajoutent des opérations spécifiques afin de respecter le plan d'entretien auto défini par le constructeur. Faire la révision de votre voiture consiste donc à faire l'ensemble de ce qui est décrit ci-dessus. Ce n'est donc pas du tout pareil que faire une vidange de votre moteur (la vidange voiture fait partie de la révision de la voiture parmi beaucoup d'autres opérations).</p>
		</p>
	</div>
	<h3><a href="#">A quel moment dois-je faire la révision de ma voiture ?</a></h3>
	<div>
		<p>
		Selon les modèles, vous devez faire la révision de votre voiture tous les 15000, 20000 ou 30000 Kms.<br/> Généralement les moteurs diesel ont la révision à faire tous les 20000 kms.<br/>
		Dans tous les cas, même si vous roulez peu avec votre voiture et qu'il faut 3 ans pour faire vos 20000 kms, la révision de votre voiture est à faire tous les 2 ans en général.<br/> En cas de doute vous pouvez nous contacter, nos conseillers seront à votre écoute.
		</p>
	</div>
	<h3><a href="#">Qu'appelle-t-on "faire le diagnostic électronique" de la voiture lors de sa révision ?</a></h3>
	<div>
		<p>
		Nous l'avons vu plus haut, lorsque l'on fait la révision de la voiture, on fait un diagnostic électronique, mais c'est quoi au juste ?<br/><br/>
		Depuis les années 2000, les voitures produites sont de plus en plus sophistiquées (meilleure tenue de route, meilleur freinage, moins polluante, moins gourmande en carburant...).<br/>Pour gérer tout cela, il y a des calculateurs dans votre voiture (sorte de petits ordinateurs) qui vérifient le bon fonctionnement de l'ensemble de ces éléments.<br/>
		L'outil de diagnostic permet de communiquer avec ces calculateurs qui, en quelque sorte, régissent votre voiture au quotidien. Ainsi, lors de la lecture, on peut par exemple vérifier le bon fonctionnement d'éléments du moteur sans avoir à le démonter ou encore télécharger des programmes permettant une amélioration des caractéristiques du moteur.<br/> La moyenne d'âge des voitures qui roulent en France est 8,2 ans en 2008. Si on extrapole, 1 voiture sur 2 est concernée par la lecture des calculateurs de la voiture par un outil de diagnostic. Cette prestation est donc récente et encore peu connue. Il y a 15 ans, ce n'était pas aussi complexe. La révision de votre voiture est donc très importante et il ne faut pas la négliger.
		En révisant sa voiture, on protège son bien et on se prémunit de problèmes beaucoup plus graves et par conséquent plus onéreux.
		</p>
	</div>
</div>

</div>			
				
<p class="blc-txt">Enfin, entretenir son auto, c'est protéger l'environnement !</p>

<div class="center demo" style="display:none">
	<a href="<?php echo $this->url(array('controller'=>'service','action'=>'forfaits'),'default',true) ?>">Voir Tous Nos Forfaits</a>
</div>

          </div>
          </div>
        
        <?php echo $this->partial('commun/sidebar.phtml') ?>

      </div>
	
	<script>
	$(function() {
		$( "#accordion" ).accordion();
		$( "input:submit, a, button", ".demo" ).button();
	});
	</script>