      <div class="container clearfix">
        <div id="default-page" class="main-con">
          <div class="title-nav">
            <h2 style="background-position:0 -382px">Plaque d'Immatriculation</h2>
          </div>
          <div class="content" style="margin-bottom:50px">
            <div class="divpic">
            	<img src="<?php echo $this->baseUrl('image/automonp/immat.jpg')?>" alt="pneumatique voiture" class="pic"/>
            	<img src="<?php echo $this->baseUrl('image/automonp/immat2.jpg')?>" alt="pneumatique voiture" class="pic"/>
            </div>
    
<p class="blc-txt">
	Depuis la mise en place du système d'immatriculation des véhicules (SIV) en avril 2009, les séries
	de lettre à droite de la plaque défilent à vitesse grand V, à tel point qu'on peut tout simplement
	tomber sur n'importe quelle combinaison de lettres. Or, si le gouvernement a choisi d'écarter la
	série SS, comme c'était le cas dans l'ancien système d'immatriculation, il reste un bon nombre
	de combinaisons disgracieuses telles que : FN, KK, PD, PQ, PT, QQ, WC...
</p>
<p class="blc-txt">
	<strong>AUTOMOBILES MONPLAISIR</strong> dispose des compétences et des outils nécessaire à la pose des plaques
	d’immatriculation en aluminium (52 X 11 cm)
</p>
<p class="blc-txt">
	
	<dl>
		Le principe de numérotation est le suivant :
		<dt><span class="blue">&bull;</span> de AA-001-AA à AA-999-AA (les chiffres évoluent en premier)</dt>
		<dt><span class="blue">&bull;</span> de AA-001-AB à AA-999-AZ (2e élément lettres de droite)</dt>
		<dt><span class="blue">&bull;</span> de AA-001-BA à AA-999-ZZ (1er élément lettres de droite)</dt>
		<dt><span class="blue">&bull;</span> de AB-001-AA à AZ-999-ZZ (2e élément lettres de gauche)</dt>
		<dt><span class="blue">&bull;</span> de BA-001-AA à ZZ-999-ZZ (1er élément lettres de gauche)</dt>
	</dl>
</p>
<p class="blc-txt">
	La numérotation des véhicules se fait de manière séquentielle et au niveau national (de AA-001-
	AA à ZZ-999-ZZ). L'identifiant territorial, finalement obligatoire, est au choix du propriétaire et
	comprend un emblème régional surmontant un numéro de département inclus dans la région
	choisie.
</p>

</p>
        
<div>

<div id="accordion">
	<h3><a href="#"><strong>Conseils de Pros</strong></a></h3>
	<div>
		<p>
		<p> <span class="blue">&bull;</span> Vous venez d’acquérir un véhicule d’occasion, vous devez changer vos plaques d’immatriculation.</p><br/>
		<p> <span class="blue">&bull;</span> Pour des raisons de sécurités, vos plaques doivent être lisible et en bon état.<p><br/>
		<p> <span class="blue">&bull;</span> Avant de vous présenter au centre de contrôle technique, pensez à vérifier l’état de vos plaques d’immatriculation car si celles-ci sont détériorées, vous serez dans l’obligation de les remplacer. Nous sommes à votre disposition.
		</p>
	</div>
</div>

</div>

          </div>
          
        </div>
        
        <?php echo $this->partial('commun/sidebar.phtml') ?>

      </div>
    
    <script>
	$(function() {
		$( "#accordion" ).accordion();
	});
	</script>
    