	<div class="container clearfix">
		<div id="default-page" class="main-con">
			<div class="title-nav">
				<h2 style="background-position:0 -166px">Nos Services Plus</h2>
			</div>
		<div class="content" style="font-size:13px;margin-bottom:50px">
			<p style="font-weight:bold" class="blc-txt">
				Automobiles Monplaisir met tout en œuvre pour vous offrir la meilleure qualité de service possible car votre satisfaction est notre première motivation et notre meilleure publicité.
			</p>
			
			<dl class="nos-plus">
			<dt>Nous avons fait le choix du service client</dt>
				<dd>&bull; Accueil de qualité et réactivité pour nos interventions</dd>
				<dd>&bull; Prêt de véhicule GRATUIT (selon disponibilité)</dd>
				<dd>&bull; Devis personnalisés</dd>
				<dd>&bull; Paiement jusqu'à 4 fois SANS FRAIS</dd>
				<dd>&bull; Conformité des interventions par rapport à l’ordre de réparation signé par le client</dd>
				<dd>&bull; Conseils et écoute</dd>
			
			<dt>Nous avons fait le choix de la qualité</dt>
				<dd>&bull; Toutes nos pièces sont garanties 1 ou 2 an(s) (selon constructeurs)</dd>
				<dd>&bull; Respect des règlementations en vigueur</dd>
				<dd>&bull; Respect de l'environnement</dd>
				<dd>&bull; Interventions dans le respect de la sécurité</dd>
			</dl>
			
			<p style="font-weight:bold" class="blc-txt">
				AUTOMOBILES MONPLAISIR est à votre écoute...
			</p>
			
        </div>
        
        </div>
        
        <?php echo $this->partial('commun/sidebar.phtml') ?>

      </div>
	
	<script>
	$(function() {

	});
	</script>