      <div class="container clearfix">
        <div id="default-page" class="main-con">
          <div class="title-nav">
            <h2 style="background-position:0 -382px">Pneumatique</h2>
          </div>
          <div class="content" style="margin-bottom:50px">
            <div class="divpic">
            	<img src="<?php echo $this->baseUrl('image/automonp/pneu.jpg')?>" alt="pneumatique voiture" class="pic"/>
            	<img src="<?php echo $this->baseUrl('image/automonp/pneu3.jpg')?>" alt="pneumatique voiture" class="pic"/>
            </div>
    
<p class="blc-txt"><strong>Le Garage Automobiles Monplaisir</strong> vous propose un large choix de pneus tout au long de l’année.</p>
        
<div>

<div id="accordion">
	<h3><a href="#"><strong>3 Points Importants</strong></a></h3>
	<div>
		<p>
		<p> <span class="blue">&bull;</span> Des pneus en bon état et bien gonflés, c'est indispensable pour votre sécurité.Le niveau d'usure et le gonflage de vos pneus sont des indicateurs essentiels de votre sécurité sur la route par tous les temps.</p><br/>
		<p> <span class="blue">&bull;</span> Pensez à vérifier chaque mois la pression, le témoin d'usure et l'état de vos pneus. De simples contrôles de routine vous permettent d'évaluer l'état de vos pneumatiques dans votre quotidien ou avant un long trajet.<p><br/>
		<p> <span class="blue">&bull;</span> Un diagnostic gratuit et sans RDV!</p>
		</p>
	</div>
</div>

<p class="blc-txt">Un technicien effectue un bilan gratuit et vous oriente vers nos solutions d'entretien les plus adaptées.<br/> Seul élément du véhicule en contact avec la route, quel que soit l'état de celle-ci (mouillée, verglas...), les pneus doivent toujours être en bon état et bien gonflés, sinon les conséquences peuvent être très vite graves : pneu qui éclate, sortie de route, dérapage, aquaplaning... Au moindre signe d'usure, il ne faut pas hésiter à les faire contrôler.</p>

</div>

          </div>
          
        </div>
        
        <?php echo $this->partial('commun/sidebar.phtml') ?>

      </div>
    
    <script>
	$(function() {
		$( "#accordion" ).accordion();
	});
	</script>
    