      <div class="container clearfix">
        <div id="default-page" class="main-con">
          <div class="title-nav">
            <h2 style="background-position:0 -382px">Pare-Brise et Vitrage</h2>
          </div>
          <div class="content" style="margin-bottom:50px">
            <div class="divpic">
            	<img src="<?php echo $this->baseUrl('image/automonp/vitrage1.jpg')?>" alt="pare-brise vitrage voiture" class="pic"/>
            	<img src="<?php echo $this->baseUrl('image/automonp/vitrage2.jpg')?>" alt="pare-brise vitrage voiture" class="pic"/>
            </div>
            
<div class="">

<p class="blc-txt">
En plus de protéger les occupants du vent, le pare-brise est essentiel pour la rigidité du véhicule. Sa
fragilisation diminue globalement la sécurité du véhicule en réduisant la visibilité du conducteur et la
protection des passagers en cas de collision.<br/>
Il peut arriver qu’un gravillon heurte la couche extérieure du pare-brise. Ce choc se traduit dans le
meilleur des cas, par un impact en forme de bulle étoilée (réparable si de faible dimension) ou au pire,
par une fissure.
</p>

<div id="accordion">
	<h3><a href="#"><strong>Conseils de Pros</strong></a></h3>
	<div>
		<p>
			<p>Ne tardez pas à faire réparer l’impact sous peine qu’il ne s’agrandisse. Une réparation de pare brise effectuée à temps peut vous éviter son remplacement total.</p><br/>
			<p>En attendant la réparation d’un impact :</p>
				<p><span class="blue">&bull;</span> Apposer une pastille de protection sur l’impact qui le protégera de la pollution et des souillures en attendant la réparation.</p>
				<p><span class="blue">&bull;</span> Franchir les trottoirs et les ralentisseurs avec précaution.</p>
				<p><span class="blue">&bull;</span> Eviter autant que possible les nids de poule et autres reliefs de la route.</p>
				<p><span class="blue">&bull;</span> Eviter les chocs thermiques en ajustant par palier la température intérieure air (chaud ou froid).</p>
		</p>
	</div>
</div>

</div>

          </div>
          
        </div>
        
        <?php echo $this->partial('commun/sidebar.phtml') ?>

      </div>
    
    <script>
	$(function() {
		$( "#accordion" ).accordion();
	});
	</script>
    