   	<div class="slide-box mod-con" style="display:block">
      <ul class="slide-player">
       <!--	<li class="selected"><a href="http://www.automonplaisir.fr/service/entretien"><img src="<?php// echo $this->baseUrl('image/slideshow/autmonplaisir-promo_automne-banniere.jpg')?>" alt="" /></a></li>-->
        <li class="selected"><a href="<?php echo $this->url(array('controller'=>'service','action'=>'entretien'),'default',true) ?>"><img src="<?php echo $this->baseUrl('image/slideshow/printemps2015_ban.jpg')?>" alt="" /></a></li>
        <li class=""><a href="<?php echo $this->url(array('controller'=>'service','action'=>'siv'),'default',true) ?>"><img src="<?php echo $this->baseUrl('image/slideshow/siv.jpg')?>" alt="" /></a></li>
        <li><a href="#"><img src="<?php echo $this->baseUrl('image/slideshow/batterie.jpg')?>" alt="" /></a></li>
      </ul>
      <div class="slide-menu"> <a href="#" class="selected">1</a> <a href="#">2</a> <a href="#">3</a></div>
    </div>
